# Generated by Django 3.2.8 on 2022-02-15 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_barras', models.CharField(max_length=20)),
                ('cd_bloco', models.CharField(max_length=3)),
                ('qt_fileiras_pallet', models.IntegerField()),
                ('sn_ativo', models.BooleanField(default=True)),
                ('sn_deletado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_barras', models.CharField(max_length=20)),
                ('tp_embalagem', models.CharField(choices=[('GARRAFA', 'GARRAFA'), ('UNIDADE', 'UNIDADE'), ('BANDEJA', 'BANDEJA'), ('BALDE', 'BALDE'), ('LITRO', 'LITRO'), ('QUILOGRAMA', 'QUILOGRAMA')], max_length=10)),
                ('qt_unidade', models.IntegerField()),
                ('dt_fabricacao', models.DateField(auto_now=True)),
                ('sn_sobra', models.BooleanField(default=False)),
                ('sn_armazenado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_produto', models.CharField(max_length=500)),
                ('cd_interno', models.IntegerField()),
                ('cd_barras', models.CharField(max_length=20)),
                ('prazo_validade', models.IntegerField()),
                ('qt_unid_cx_papelao', models.IntegerField()),
                ('qt_unid_cx_plastico', models.IntegerField()),
                ('sn_ativo', models.BooleanField(default=True)),
                ('sn_deletado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_rua', models.CharField(max_length=50)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('sn_deletado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_ativo', models.BooleanField(default=True)),
                ('sn_deletado', models.BooleanField(default=True)),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('rua_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.rua')),
            ],
        ),
        migrations.CreateModel(
            name='PalletBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_entrada', models.DateField(auto_now=True)),
                ('dt_saida', models.DateField(blank=True, null=True)),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.bloco')),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.pallet')),
            ],
        ),
        migrations.AddField(
            model_name='pallet',
            name='produto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.CreateModel(
            name='Paleteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_paleteira', models.IntegerField()),
                ('tp_paleteira', models.CharField(choices=[('C', 'CORREDOR'), ('N', 'NORMAL')], default='N', max_length=2)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('sn_deletado', models.BooleanField(default=True)),
                ('rua_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.rua')),
            ],
        ),
        migrations.CreateModel(
            name='MovPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_unidade', models.IntegerField()),
                ('tp_movimentacao', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=10)),
                ('dt_movimentacao', models.DateField(auto_now=True)),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.pallet')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_unidade', models.IntegerField()),
                ('sn_ativo', models.BooleanField(default=True)),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.pallet')),
            ],
        ),
        migrations.AddField(
            model_name='bloco',
            name='paleteira_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.paleteira'),
        ),
    ]
