# Generated by Django 3.2.8 on 2021-12-11 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeArmazem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Palet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=20, unique=True)),
                ('dataCriacao', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidadeItens', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('codigoBarras', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSetor', models.CharField(max_length=50)),
                ('codigoBarras', models.CharField(max_length=20, unique=True)),
                ('dataCriacao', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.armazem')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCaixa', models.CharField(max_length=20)),
                ('quantidadeProdutosTipoCaixa', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SetorLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna', models.IntegerField()),
                ('linha', models.IntegerField()),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.setor')),
            ],
        ),
        migrations.CreateModel(
            name='PaletSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicoAlocacao', models.DateField(default=django.utils.timezone.now)),
                ('dataFimAlocacao', models.DateField(blank=True, null=True)),
                ('palet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.palet')),
                ('setorLocalizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.setorlocalizacao')),
            ],
        ),
        migrations.AddField(
            model_name='palet',
            name='tipoCaixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipocaixa'),
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=20, unique=True)),
                ('dataFabricacao', models.DateField(default=django.utils.timezone.now)),
                ('dataSaide', models.DateField(blank=True, null=True)),
                ('quantidadeProdutosCaixa', models.IntegerField()),
                ('palet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.palet')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('tipoCaixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipocaixa')),
            ],
        ),
    ]
