# Generated by Django 3.2.8 on 2021-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeArmazem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=20, unique=True)),
                ('dataFabricacao', models.DateField(auto_now=True)),
                ('dataSaide', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Palet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=20, unique=True)),
                ('dataCriacao', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidadeItens', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSetor', models.CharField(max_length=50)),
                ('codigoBarras', models.CharField(max_length=20, unique=True)),
                ('dataCriacao', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
