# Generated by Django 3.2.8 on 2021-10-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='palet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.palet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='armazem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.armazem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caixa',
            name='dataSaide',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaletSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicoAlocacao', models.DateField(auto_now=True)),
                ('dataFimAlocacao', models.DateField(blank=True, null=True)),
                ('palet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.palet')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.setor')),
            ],
        ),
    ]
