# Generated by Django 3.2.8 on 2021-12-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20211212_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='palet',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
            preserve_default=False,
        ),
    ]
