# Generated by Django 3.2.8 on 2022-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20220215_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='sn_sobra',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
    ]
