# Generated by Django 3.2.8 on 2021-12-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20211215_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='superPalet',
        ),
    ]
