# Generated by Django 3.2.8 on 2021-12-15 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_superpalet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superpalet',
            name='dataCriacao',
        ),
        migrations.AddField(
            model_name='superpalet',
            name='dataRetirada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='superpalet',
            name='codigoBarras',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='superpalet',
            name='dataArmazenamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
