# Generated by Django 3.2.8 on 2021-12-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_auto_20211215_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpalet',
            name='codigoBarras',
            field=models.CharField(max_length=40),
        ),
    ]
