# Generated by Django 3.2.8 on 2021-12-15 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_alter_superpalet_codigobarras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpalet',
            name='dataArmazenamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='superpalet',
            name='dataRetirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
