# Generated by Django 3.2.8 on 2021-12-15 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_auto_20211215_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpalet',
            name='dataArmazenamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='superpalet',
            name='dataRetirada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
