# Generated by Django 3.2.8 on 2021-12-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_notafiscal_notafiscalproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='palet',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='tipoCaixa',
        ),
        migrations.RemoveField(
            model_name='palet',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='palet',
            name='tipoCaixa',
        ),
        migrations.RemoveField(
            model_name='paletsetor',
            name='palet',
        ),
        migrations.RemoveField(
            model_name='paletsetor',
            name='setorLocalizacao',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='armazem',
        ),
        migrations.RemoveField(
            model_name='setorlocalizacao',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='tipocaixa',
            name='produto',
        ),
        migrations.AlterField(
            model_name='superpalet',
            name='tipoEmbalagem',
            field=models.CharField(choices=[('PA', 'PAPELÃO'), ('PL', 'PLÁSTICO')], default='PA', max_length=2),
        ),
        migrations.DeleteModel(
            name='Armazem',
        ),
        migrations.DeleteModel(
            name='Caixa',
        ),
        migrations.DeleteModel(
            name='Palet',
        ),
        migrations.DeleteModel(
            name='PaletSetor',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
        migrations.DeleteModel(
            name='SetorLocalizacao',
        ),
        migrations.DeleteModel(
            name='TipoCaixa',
        ),
    ]
