# Generated by Django 3.2.8 on 2021-12-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_auto_20211224_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('CONFERIDA', 'CONFERIDA'), ('FINALIZADA', 'FINALIZADA')], default='ABERTA', max_length=20),
        ),
    ]
